task_manager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import TemplateView

from task_manager.users.views import (
    UserCreateView,
    UserLogoutView,
)

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("admin/", admin.site.urls),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("users/create/", UserCreateView.as_view(), name="register"),
    path("users/", include("task_manager.users.urls")),
    path("statuses/", include("task_manager.statuses.urls")),
    path("labels/", include("task_manager.labels.urls")),
    path("tasks/", include("task_manager.tasks.urls")),
    path('login/',
         auth_views.LoginView.as_view(
             template_name='users/login.html',
             redirect_authenticated_user=True
         ),
         name='login'),
]

task_manager/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UsersIndexView.as_view(), name='index'),
    path('create/', views.UserCreateView.as_view(), name='user_create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    first_name = models.CharField(_("first name"), max_length=150, blank=False)
    last_name = models.CharField(_("last name"), max_length=150, blank=False)

    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

task_manager/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

User = get_user_model()


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(
        label=_("Пароль"),
        widget=forms.PasswordInput,
        strip=False,
    )
    password2 = forms.CharField(
        label=_("Подтверждение пароля"),
        widget=forms.PasswordInput,
        strip=False,
    )

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
        )
        labels = {
            "first_name": _("Имя"),
            "last_name": _("Фамилия"),
            "username": _("Имя пользователя"),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError(
                _("Пароли не совпадают."),
                code="password_mismatch",
            )
        return password2

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if password1 and len(password1) < 3:
            raise ValidationError(
                _(
                    "Этот пароль слишком короткий. "
                    "Он должен содержать не менее 3 символов."
                ),
                code="password_too_short",
            )
        return password1

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserUpdateForm(forms.ModelForm):
    password1 = forms.CharField(
        label=_("Пароль"),
        widget=forms.PasswordInput,
        strip=False,
        required=False,
    )
    password2 = forms.CharField(
        label=_("Подтверждение пароля"),
        widget=forms.PasswordInput,
        strip=False,
        required=False,
    )
    username = forms.CharField(
        label=_("Имя пользователя"),
        required=False,
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
        )
        labels = {
            "first_name": _("Имя"),
            "last_name": _("Фамилия"),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 or password2:
            if not password1 or not password2:
                self.add_error(
                    "password2",
                    _("Пожалуйста, заполните оба поля для пароля.")
                )
            elif password1 != password2:
                self.add_error("password2", _("Пароли не совпадают."))
        return password2

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        if password1 and len(password1) < 3:
            raise ValidationError(
                _(
                    "Этот пароль слишком короткий. "
                    "Он должен содержать не менее 3 символов."
                ),
                code="password_too_short",
            )
        return password1

    def save(self, commit=True):
        user = super().save(commit=False)
        password1 = self.cleaned_data.get("password1")
        if password1:
            user.set_password(password1)
        if commit:
            user.save()
        return user

task_manager/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import (
    LoginRequiredMessageMixin,
)
from task_manager.tasks.models import Task

User = get_user_model()

USERS_INDEX_URL = "users:index"


class UsersIndexView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'


class UserCreateView(SuccessMessageMixin, CreateView):
    model = User
    template_name = "users/registration_form.html"
    success_url = reverse_lazy("login")
    success_message = _("Пользователь успешно зарегистрирован")
    extra_context = {
        "title": _("Регистрация"),
        "button_text": _("Зарегистрироваться"),
    }

    def get_form_class(self):
        from .forms import UserCreationForm
        return UserCreationForm


class UserLoginView(LoginRequiredMessageMixin,
                    SuccessMessageMixin, CreateView):
    template_name = "users/login.html"
    success_url = reverse_lazy("index")
    success_message = _("Вы залогинены")
    extra_context = {
        "title": _("Вход"),
        "button_text": _("Войти"),
    }

    def get_form_class(self):
        from django.contrib.auth.forms import AuthenticationForm
        return AuthenticationForm

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            messages.success(self.request, _("Вы залогинены"))
            return redirect(self.get_success_url())
        return self.form_invalid(form)


class UserLogoutView(View):
    def get(self, request, *args, **kwargs):
        was_authenticated = request.user.is_authenticated
        logout(request)
        if was_authenticated:
            messages.success(request, _("Вы разлогинены"))
        return redirect("index")


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = "users/user_list.html"
    context_object_name = "users"


class UserUpdateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    UpdateView
):
    model = User
    template_name = "users/user_edit.html"
    success_url = reverse_lazy(USERS_INDEX_URL)
    success_message = _("Пользователь успешно изменен")
    permission_denied_message = _(
        "У вас нет прав для изменения другого пользователя."
    )
    extra_context = {
        "title": _("Редактировать профиль"),
        "button_text": _("Изменить"),
    }

    def get_form_class(self):
        from .forms import UserUpdateForm
        return UserUpdateForm


class UserDeleteView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    DeleteView
):
    model = User
    template_name = "users/user_delete.html"
    success_url = reverse_lazy("users:index")
    success_message = _("Пользователь успешно удален")

    def dispatch(self, request, *args, **kwargs):
        user = self.get_object()
        
        # Проверка прав (нельзя удалять чужого юзера)
        if request.user.id != user.id:
            messages.error(
                request,
                _("У вас нет прав для изменения другого пользователя.")
            )
            return redirect("users:index")

        # Проверка связанных задач
        if Task.objects.filter(Q(author=user) | Q(executor=user)).exists():
            messages.error(
                request,
                _("Невозможно удалить пользователя, потому что он используется")
            )
            return redirect("users:index")
        
        return super().dispatch(request, *args, **kwargs)

task_manager/users/templates/users/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>{% block title %}Task Manager{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container mt-4">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

task_manager/users/templates/users/baseus.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>{% block title %}Task Manager{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
  <div class="container mt-4">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

task_manager/users/templates/users/index.html
<!-- templates/users/index.html -->
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <h1 class="my-4">Пользователи</h1>
  
  {% if users %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Имя пользователя</th>
          <th>Полное имя</th>
          <th>Дата создания</th>
          <th>Действия</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
          <tr>
            <td>{{ user.pk }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }} {{ user.last_name }}</td>
            <td>{{ user.date_joined|date:"d.m.Y H:i" }}</td>
            <td>
              <a href="{% url 'users:update' user.pk %}">Изменить</a>
              <br>
              <a href="{% url 'users:delete' user.pk %}">Удалить</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>Пользователей пока нет.</p>
  {% endif %}
{% endblock %}

task_manager/users/templates/users/login.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% load i18n %}

{% block content %}
<h2 class="my-4">{% trans "Login" %}</h2>
  
<form method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% trans 'Log in' as login_text %}
  {% bootstrap_button login_text button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/users/templates/users/register.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">Регистрация нового пользователя</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    
                    <div class="mb-3">
                        <label for="{{ form.username.id_for_label }}" class="form-label">Имя пользователя *</label>
                        {{ form.username|bootstrap_field }}
                    </div>
                    
                    <div class="mb-3">
                        <label for="{{ form.password1.id_for_label }}" class="form-label">Пароль *</label>
                        {{ form.password1|bootstrap_field }}
                    </div>
                    
                    <div class="mb-3">
                        <label for="{{ form.password2.id_for_label }}" class="form-label">Подтверждение пароля *</label>
                        {{ form.password2|bootstrap_field }}
                    </div>
                    
                    <div class="mb-3">
                        <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                        {{ form.email|bootstrap_field }}
                    </div>
                    
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label">Имя</label>
                            {{ form.first_name|bootstrap_form form}}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label">Фамилия</label>
                            {{ form.last_name|bootstrap_field }}
                        </div>
                    </div>
                    
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-success">Зарегистрировать</button>
                        <a href="{% url 'users:index' %}" class="btn btn-secondary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/users/templates/users/registration_form.html
<!-- templates/users/registration_form.html -->
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="row justify-content-center mt-5">
    <div class="col-md-6">
      <h2 class="text-center mb-4">{{ title|default:"Регистрация" }}</h2>
      <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-primary w-100">{{ button_name|default:"Зарегистрировать" }}</button>
      </form>
      <div class="text-center mt-3">
        <a href="{% url 'login' %}">Уже есть аккаунт? Войти</a>
      </div>
    </div>
  </div>
{% endblock %}

task_manager/users/templates/users/user_confirm_delete.html
<!-- templates/users/user_delete.html -->
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">Подтверждение удаления</h4>
            </div>
            <div class="card-body text-center">
                <div class="mb-4">
                    <i class="bi bi-exclamation-triangle text-warning" style="font-size: 3rem;"></i>
                </div>
                
                <h5>Вы уверены, что хотите удалить пользователя?</h5>
                <p class="text-muted">Пользователь: <strong>{{ user.username }}</strong></p>
                <p class="text-danger">Это действие нельзя отменить!</p>
                
                <form method="post">
                    {% csrf_token %}
                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-danger">Да, удалить</button>
                        <a href="{% url 'users:index' %}" class="btn btn-secondary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/users/templates/users/user_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>Удаление пользователя</h1>
    
    <p>Вы уверены, что хотите удалить пользователя "{{ object.username }}"?</p>

    <form method="post" action="{% url 'users:delete' object.id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-danger">Да, удалить</button>
    </form>
</div>
{% endblock %}

task_manager/users/templates/users/user_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block title %}Редактирование пользователя{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">Редактирование: {{ object.username }}</h4>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}

                    <div class="d-grid gap-2">
                        <button type="submit" class="btn btn-primary">Изменить</button>
                        <a href="{% url 'users:index' %}" class="btn btn-secondary">Отмена</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

task_manager/users/templates/users/user_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block title %}Список пользователей{% endblock %}
{% block content %}
<div class="d-flex justify-content between align-items-center mb-4">
    <h1>Список пользователей</h1>
    {% if user.is_authenticated and user.is_staff %}
        <a href="{% url "register" %}" class="btn btn-success">
            <i class="bi bi-person-plus"></i>Создать пользователя
        </a>
    {% endif %}
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Имя</th>
                <th>Фамилия</th>
                <th>Staff</th>
                <th>Active</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for user_obj in users %}
            <tr>
                <td>{{ user_obj.id }}</td>
                <td>{{ user_obj.username }}</td>
                <td>{{ user_obj.email }}</td>
                <td>{{ user_obj.first_name }}</td>
                <td>{{ user_obj.last_name }}</td>
                <td>
                    {% if user_obj.is_staff %}
                        <span class="badge bg-success">Да</span>
                    {% else %}
                        <span class="badge bg-secondary">Нет</span>
                    {% endif %}
                </td>
                <td>
                    {% if user_obj.is_active %}
                        <span class="badge bg-success">Да</span>
                    {% else %}
                        <span class="badge bg-danger">Нет</span>
                    {% endif %}
                </td>
                <td>
                    <div class="btn-group btn-group-sm">
                        {% if user.is_authenticated %}
                            <a href="{% url 'users:update' user_obj.id %}" class="btn btn-outline-primary">
                                Редактировать
                            </a>
                            
                            {# ВРЕМЕННО ДЛЯ ТЕСТОВ: показываем кнопку удаления всем #}
                            <a href="{% url 'users:delete' user_obj.id %}" class="btn btn-outline-danger">
                                Удалить
                            </a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="8" class="text-center text-muted">Пользователи не найдены</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}